module.exports = {
  fakeMarkdown:
    'Bonjour, je suis **Renaud**, fondateur de [NovaGaïa](https://novagaia.fr).\n- Item 1\n- Item 2',
  fakeMarkdownWithImage: (imgName) => {
    return `Bonjour, je suis Renaud, fondateur de [NovaGaïa](https://novagaia.fr).\n![Event 2022](/uploads/${imgName})`;
  },
  fakeImage: {
    data: {
      id: 1,
      attributes: {
        name: 'anita-austvika-ornoDnE8E4A-unsplash.jpg',
        alternativeText: null,
        caption: null,
        width: 1600,
        height: 900,
        formats: {
          thumbnail: {
            name: 'anita-austvika-ornoDnE8E4A-unsplash.jpg',
            hash: 'anita-austvika-ornoDnE8E4A-unsplash',
            ext: '.jpg',
            mime: 'image/jpeg',
            path: null,
            width: 245,
            height: 138,
            size: 8.9,
            url: `https://github.com/NovaGaia/strapi-plugin-mock-datas/blob/main/mocking-assets/anita-austvika-ornoDnE8E4A-unsplash.jpg?raw=true`,
          },
          small: {
            name: 'anita-austvika-ornoDnE8E4A-unsplash.jpg',
            hash: 'anita-austvika-ornoDnE8E4A-unsplash',
            ext: '.jpg',
            mime: 'image/jpeg',
            path: null,
            width: 500,
            height: 281,
            size: 36.38,
            url: 'https://github.com/NovaGaia/strapi-plugin-mock-datas/blob/main/mocking-assets/anita-austvika-ornoDnE8E4A-unsplash.jpg?raw=true',
          },
          medium: {
            name: 'anita-austvika-ornoDnE8E4A-unsplash.jpg',
            hash: 'anita-austvika-ornoDnE8E4A-unsplash',
            ext: '.jpg',
            mime: 'image/jpeg',
            path: null,
            width: 750,
            height: 422,
            size: 84.38,
            url: 'https://github.com/NovaGaia/strapi-plugin-mock-datas/blob/main/mocking-assets/anita-austvika-ornoDnE8E4A-unsplash.jpg?raw=true',
          },
          large: {
            name: 'anita-austvika-ornoDnE8E4A-unsplash.jpg',
            hash: 'anita-austvika-ornoDnE8E4A-unsplash',
            ext: '.jpg',
            mime: 'image/jpeg',
            path: null,
            width: 1000,
            height: 563,
            size: 152.43,
            url: 'https://github.com/NovaGaia/strapi-plugin-mock-datas/blob/main/mocking-assets/anita-austvika-ornoDnE8E4A-unsplash.jpg?raw=true',
          },
        },
        hash: 'anita-austvika-ornoDnE8E4A-unsplash',
        ext: '.jpg',
        mime: 'image/jpeg',
        size: 387.73,
        url: 'https://github.com/NovaGaia/strapi-plugin-mock-datas/blob/main/mocking-assets/anita-austvika-ornoDnE8E4A-unsplash.jpg?raw=true',
        previewUrl: null,
        provider: 'local',
        provider_metadata: null,
        createdAt: '2023-03-25T07:29:21.700Z',
        updatedAt: '2023-03-25T07:29:21.700Z',
      },
    },
  },
};
